
default:
  image: node:lts

stages:
  - publish


pages:
  stage: publish
  before_script: []
  only:
    - main
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build-json
    # CI=false does not let the build fail on warnings
    - CI=false yarn build
  artifacts:
    paths:
      - build
