variables:
  AWS_REGION: eu-central-1
  AWS_BUCKET_NAME: awesome-devops20210618085129867100000003

default:
  image: node:lts

stages:
  - publish


pages:
  stage: publish
  before_script: []
  only:
    - main
  before_script:
    # install AWS CLI v2
    # @see https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build-json
    # CI=false does not let the build fail on warnings
    - CI=false yarn build
    - aws sync ./build "s3://${AWS_BUCKET_NAME}"
  artifacts:
    paths:
      - build
