
default:
  image: node:lts

stages:
  - publish


before_script:


pages:
  stage: publish
  before_script: []
  only:
    - main
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build-json
    - yarn build
  artifacts:
    paths:
      - build
